apiVersion: apps/v1
kind: Deployment
metadata:
  name: onboarding
  annotations:
    image.openshift.io/triggers: |-
      [
        {
          "from": {
            "kind": "ImageStreamTag",
            "name": "openshift-acct-mgt:develop"
          },
          "fieldPath": "spec.template.spec.containers[0].image"
        }
      ]
