apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../crc
- ./build

patches:
  - path: deployments/onboarding_patch.yaml

images:
  - name: openshift-acct-mgt
    newTag: develop
